/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pers;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.UIManager;

/**
 *
 * @author hewro
 */
public class DynamicPartitioned extends javax.swing.JFrame {
    
    /* Member variables */
    public int MainMemorySize = 1000;
    public int MainMemoryStart = 20;
    public static ArrayList<Task> tasks = new ArrayList<>();//存放作业的数组
    public static ArrayList<Partition> partitions = new ArrayList<>();//存放主存的分区
    //public static ArrayList<Partition> freePartitions = new ArrayList<>();//空闲分区
   // public static ArrayList<Partition> occupyPartitions = new ArrayList<>();//已经占用分区
    public static Partition currentPartition = new Partition();
    final static MyTableModel dtm = new MyTableModel();//表格的抽象模型
    public final static Task nullTask = new Task(0, "null");
    //public Task[] tasks = new Task[20];//最多20个作业
    //public Partition[] partitions = new Partition[20];//最多20个分区
    
    
    /**
     * Creates new form DynamicPartitioned
     */
    public DynamicPartitioned() {
        initComponents();
    }
    private static void setLookFeel() {
        try {

             // Set System L&F
             UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e) {
             System.out.println("Cannot set System look and feel. Default look and feel will be used.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AboutDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDialog5 = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        taskSizeField = new javax.swing.JTextField();
        distributeButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TaskNameTextField = new javax.swing.JTextField();
        recoveryButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        partionTable = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        aboutMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pers/Bundle"); // NOI18N
        AboutDialog.setTitle(bundle.getString("DynamicPartitioned.AboutDialog.title")); // NOI18N
        AboutDialog.setLocation(new java.awt.Point(300, 400));
        AboutDialog.setLocationByPlatform(true);
        AboutDialog.setName("AboutDialog"); // NOI18N
        AboutDialog.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setText(bundle.getString("DynamicPartitioned.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(bundle.getString("DynamicPartitioned.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(bundle.getString("DynamicPartitioned.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout AboutDialogLayout = new javax.swing.GroupLayout(AboutDialog.getContentPane());
        AboutDialog.getContentPane().setLayout(AboutDialogLayout);
        AboutDialogLayout.setHorizontalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutDialogLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(AboutDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(95, 95, 95))
        );
        AboutDialogLayout.setVerticalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jDialog1.setTitle(bundle.getString("DynamicPartitioned.jDialog1.title")); // NOI18N
        jDialog1.setLocationByPlatform(true);
        jDialog1.setName("jDialog1"); // NOI18N
        jDialog1.setSize(new java.awt.Dimension(329, 113));

        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText(bundle.getString("DynamicPartitioned.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(bundle.getString("DynamicPartitioned.jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(24, 24, 24))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jDialog2.setTitle(bundle.getString("DynamicPartitioned.jDialog2.title")); // NOI18N
        jDialog2.setIconImage(null);
        jDialog2.setLocation(new java.awt.Point(300, 400));
        jDialog2.setLocationByPlatform(true);
        jDialog2.setName("jDialog2"); // NOI18N
        jDialog2.setSize(new java.awt.Dimension(331, 103));

        jLabel13.setForeground(java.awt.Color.red);
        jLabel13.setText(bundle.getString("DynamicPartitioned.jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(bundle.getString("DynamicPartitioned.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(38, 38, 38))
        );

        jDialog3.setTitle(bundle.getString("DynamicPartitioned.jDialog3.title")); // NOI18N
        jDialog3.setLocation(new java.awt.Point(300, 400));
        jDialog3.setLocationByPlatform(true);
        jDialog3.setName("jDialog3"); // NOI18N
        jDialog3.setSize(new java.awt.Dimension(331, 100));

        jLabel15.setText(bundle.getString("DynamicPartitioned.jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setForeground(java.awt.Color.red);
        jLabel16.setText(bundle.getString("DynamicPartitioned.jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(41, 41, 41))
        );

        jDialog4.setLocation(new java.awt.Point(300, 400));
        jDialog4.setLocationByPlatform(true);
        jDialog4.setName("jDialog4"); // NOI18N
        jDialog4.setSize(new java.awt.Dimension(331, 103));

        jLabel17.setForeground(java.awt.Color.red);
        jLabel17.setText(bundle.getString("DynamicPartitioned.jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(bundle.getString("DynamicPartitioned.jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(41, 41, 41))
        );

        jDialog5.setTitle(bundle.getString("DynamicPartitioned.jDialog5.title")); // NOI18N
        jDialog5.setLocation(new java.awt.Point(300, 400));
        jDialog5.setLocationByPlatform(true);
        jDialog5.setName("jDialog5"); // NOI18N
        jDialog5.setSize(new java.awt.Dimension(331, 100));

        jLabel19.setForeground(java.awt.Color.red);
        jLabel19.setText(bundle.getString("DynamicPartitioned.jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(bundle.getString("DynamicPartitioned.jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog5Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(41, 41, 41))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("DynamicPartitioned.title")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(231, 232, 235));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel4.setText(bundle.getString("DynamicPartitioned.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText(bundle.getString("DynamicPartitioned.jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(bundle.getString("DynamicPartitioned.jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel6.setText(bundle.getString("DynamicPartitioned.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 0, 14)); // NOI18N
        jLabel5.setText(bundle.getString("DynamicPartitioned.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel8.setText(bundle.getString("DynamicPartitioned.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        taskSizeField.setName("taskSizeField"); // NOI18N

        distributeButton.setText(bundle.getString("DynamicPartitioned.distributeButton.text")); // NOI18N
        distributeButton.setName("distributeButton"); // NOI18N
        distributeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributeButtonActionPerformed(evt);
            }
        });

        jLabel9.setText(bundle.getString("DynamicPartitioned.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        TaskNameTextField.setName("TaskNameTextField"); // NOI18N

        recoveryButton.setText(bundle.getString("DynamicPartitioned.recoveryButton.text")); // NOI18N
        recoveryButton.setName("recoveryButton"); // NOI18N
        recoveryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoveryButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 0, 15)); // NOI18N
        jLabel10.setText(bundle.getString("DynamicPartitioned.jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        partionTable.setModel(dtm);
        partionTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        partionTable.setName("partionTable"); // NOI18N
        partionTable.getTableHeader().setResizingAllowed(false);
        partionTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(partionTable);
        partionTable.getAccessibleContext().setAccessibleDescription(bundle.getString("DynamicPartitioned.partionTable.AccessibleContext.accessibleDescription_2")); // NOI18N
        GlobalObject.setjScrollPane(jScrollPane1);
        GlobalObject.setjTable(partionTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGap(17, 17, 17)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jMenuBar2.setName("jMenuBar2"); // NOI18N

        aboutMenu.setText(bundle.getString("DynamicPartitioned.aboutMenu.text")); // NOI18N
        aboutMenu.setName("aboutMenu"); // NOI18N
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });

        jMenuItem2.setText(bundle.getString("DynamicPartitioned.jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        aboutMenu.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText(bundle.getString("DynamicPartitioned.jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        aboutMenu.add(jMenuItem1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText(bundle.getString("DynamicPartitioned.jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        aboutMenu.add(jMenuItem3);

        jMenuBar2.add(aboutMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(distributeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taskSizeField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))))
                        .addGap(43, 43, 43)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recoveryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TaskNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(taskSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(distributeButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TaskNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(recoveryButton)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        setSize(new java.awt.Dimension(542, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:\
        AboutDialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AboutDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void distributeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributeButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("分配内存按钮已经被点击");
        int methodChoice = getMethodChoice();
        if("".equals(taskSizeField.getText())){
            jDialog3.setVisible(true);
        }else if(!isNumeric(taskSizeField.getText())){
            jDialog5.setVisible(true);
        }else if(methodChoice != -1){
            System.out.println("正确进入分配内存1");
            String taskName = GeneratingRandomNumbers.generate() + "";
            int taskSize = Integer.parseInt(taskSizeField.getText());
            Task currentTask = new Task(taskSize, taskName);
            partionAcllocation(currentTask,methodChoice);
        }
    }//GEN-LAST:event_distributeButtonActionPerformed

    private void recoveryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoveryButtonActionPerformed
        // TODO add your handling code here:
        String taskName  = TaskNameTextField.getText();
        partionRecovery(taskName);
    }//GEN-LAST:event_recoveryButtonActionPerformed
    
    /*
    * discription: partions recovery 
    */
    public void partionRecovery(String taskName){
        int flag = 0;
        int size = partitions.size();
        for(int i = 0; i< partitions.size(); i++,flag++){
            System.out.println("这是第" + i + "个分区");
            System.out.println("当前分区的作业名称" + partitions.get(i).getTask().getTaskName() + "             输入的作业名称是" + taskName);
            if (partitions.get(i).getTask().getTaskName().equals(taskName)) {
                int front = 0;
                int back = 0;
                if (i != 0){
                    System.out.println(i + "  不是第一个分区");
                    if (partitions.get(i-1).getStatus() == 0){
                        System.out.println("前一个分区为空");
                        front = 1;
                    }
                }
                if (i != partitions.size()-1){
                    System.out.println(i + "  不是最后一个分区");
                    if (partitions.get(i+1).getStatus() == 0) {
                        System.out.println("后一个分区为空");
                        back = 1;
                    }
                }
                if (front == 1 && back == 1) {
                    Partition newPartition = new Partition();
                    newPartition.setforAll(partitions.get(i-1).getStartAdress(), partitions.get(i-1).getSize() +partitions.get(i).getSize() + partitions.get(i+1).getSize(), 0, nullTask);
                    partitions.set(i -1, newPartition);
                    partitions.remove(i+1);
                    partitions.remove(i);
                }else if (front == 0 && back == 1){
                    Partition newPartition = new Partition();
                    newPartition.setforAll(partitions.get(i).getStartAdress(), partitions.get(i).getSize() +partitions.get(i+1).getSize(), 0, nullTask);
                    partitions.set(i, newPartition);
                    partitions.remove(i+1);
                }else if (front ==1 && back == 0){
                    Partition newPartition = new Partition();
                    newPartition.setforAll(partitions.get(i-1).getStartAdress(), partitions.get(i-1).getSize() + partitions.get(i).getSize(), 0, nullTask);
                    partitions.set(i-1, newPartition);
                    partitions.remove(i);
                }else if (front == 0 && back ==0){
                    Partition newPartition = new Partition();
                    newPartition.setforAll(partitions.get(i).getStartAdress(), partitions.get(i).getSize(), 0, nullTask);
                    partitions.set(i, newPartition);
                } 
                break;
            }
        }//end of for circle 
        if (flag >= size){
            System.err.println("没有该作业名称，请输入正确的作业ID:" + taskName);
            jDialog4.setVisible(true);
        }
        MyTableModel.reloadJTable(dtm);
    }
    
    /**
     * discription: Partition allocation
     */
    
    void partionAcllocation(Task task,int methodChoice){
        System.out.println("正确进入分配内存2");
        Partition nextPartition = new Partition();
        if(methodChoice == 1){
            SortByPartitionSize SortByPartitionSize = new SortByPartitionSize();
            Collections.sort(partitions,SortByPartitionSize);//将所有分区按照分区大小排序
        }
        for(int i=0; i< partitions.size();i++){
            System.out.print("(分配前)第" + i + "个分区的大小为" + currentPartition.getSize());
            for (int j = 1; j<5; j++) {
                System.out.print("(分配前)第" + j + "位置:" + partitions.get(i).getByIndex(j) + "   ");
            }
            System.out.println("");
        }
        int size = partitions.size();//必须是之前的分区个数
        int flag = 0;
        for(int i=0; i < partitions.size();i++,flag++){
            currentPartition = partitions.get(i);
            if(currentPartition.status == 0 && currentPartition.getSize() >= task.getSize()){
                
                System.out.println("");
                System.out.print("当前分区信息：");
                for(int k=0; k< 5; k++){
                    System.out.print("第" + k +"位置：" + currentPartition.getByIndex(k));
                }
                System.out.println("");
                
                int result = currentPartition.getStartAdress() + task.getSize();
                
                System.out.println("当前分区+作业大小:   " + result + "    当前分区大小:   " + currentPartition.getStartAdress() + "   作业大小:   "+ task.getSize());
                                
                nextPartition.setforAll(currentPartition.getStartAdress() + task.getSize(),
                    currentPartition.size - task.size, 0, nullTask);
                currentPartition.setforAll(currentPartition.getStartAdress(), 
                    task.getSize(), 1, task);
                
                System.out.println("");
                
               
                
                System.out.print("下一个插入的信息：");
                for(int k=0; k< 5; k++){
                    System.out.print("第" + k +"位置：" + nextPartition.getByIndex(k));
                }
                System.out.println("");

                System.out.println("");
                System.out.print("当前分区信息（修改后）：");
                for(int k=0; k< 5; k++){
                    System.out.print("第" + k +"位置：" + currentPartition.getByIndex(k));
                }
                System.out.println("");
                
                
                partitions.set(i, currentPartition);
                if(nextPartition.getSize()!=0){
                    partitions.add(i+1, nextPartition);    
                }
                //MyTableModel.reloadJTable(dtm);
                break;
            }
        }//end of for circle 
        if (flag >= size) {
            System.err.println("内存空间不够！");
            jDialog1.setVisible(true);
        }
        MyTableModel.reloadJTable(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DynamicPartitioned.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DynamicPartitioned.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DynamicPartitioned.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DynamicPartitioned.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setLookFeel();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DynamicPartitioned().setVisible(true);//set a new instance and set it visible
            }
        });
        initPartion(1200,20,0,nullTask);
        /*这个地方如果再次新建mainInstance实例，会导致表头重复，原因不明，解决方法是让jtable不设置为静态*/
        //DynamicPartitioned mainInstance = new DynamicPartitioned();
        MyTableModel.reloadJTable(dtm);
        
    }//end of main() method

    public static void initPartion(int size, int startAddress, int status, Task task){
        currentPartition.setSize(size);
        currentPartition.setStartAddress(startAddress);
        currentPartition.setStatus(status);
        currentPartition.setTask(task);
        //partionsAdd();
        partitions.add(currentPartition);//在分区表中添加首个大分区
        //dtm.setValueAt("2", 0, 0);
        //dtm.setValueAt("2", 0, 4);
        //System.err.println("pers.DynamicPartitioned.initPartion()");
    }
    
    public static void partionsAdd(){
        if (currentPartition.getStatus() == 0) {
            //freePartitions.add(currentPartition);
        }else{
            //occupyPartitions.add(currentPartition);
        }
        partitions.add(currentPartition);//在分区表中添加首个大分区
    }
    
    public int getMethodChoice(){
        if(jRadioButton1.isSelected() == false && jRadioButton2.isSelected() == false){
            jDialog2.setVisible(true);
            return -1;
        }else{
            if(jRadioButton1.isSelected() == true){
                System.out.println("算法1被选中");
                return 1;
            }
            else{
                System.out.println("算法2被选中");
               return 2; 
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog AboutDialog;
    public javax.swing.JTextField TaskNameTextField;
    public javax.swing.JMenu aboutMenu;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton distributeButton;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JDialog jDialog2;
    public javax.swing.JDialog jDialog3;
    public javax.swing.JDialog jDialog4;
    public javax.swing.JDialog jDialog5;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable partionTable;
    public javax.swing.JButton recoveryButton;
    public javax.swing.JTextField taskSizeField;
    // End of variables declaration//GEN-END:variables

    private boolean isNumeric(String str) {
	for (int i = str.length();--i>=0;){    
            if (!Character.isDigit(str.charAt(i))){  
		return false;  
            }  
	}  
            return true;  
    }  
}
